name: Update and Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "RClone version to build bindings for"
        required: true
        type: string
      publish:
        description: "Publish to PyPI"
        required: true
        type: boolean
        default: false
      release:
        description: "Create a GitHub release"
        required: true
        type: boolean
        default: false
jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      VERSION: ${{ github.event.inputs.version || github.event.release.tag_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Fuse bindings
      shell: bash
      run: |
        sudo modprobe fuse
        sudo chmod 666 /dev/fuse
        sudo chown root:$USER /etc/fuse.conf
        sudo apt-get update
        sudo apt-get install -y fuse3 libfuse-dev rpm pkg-config git-annex git-annex-remote-rclone nfs-common

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipx
        python -m pipx ensurepath
    
    - name: Install poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Configure Poetry
      run: poetry config virtualenvs.create false
        
    - name: Set version
      run: poetry version ${{ env.VERSION }}
    
    - name: Build package
      run: poetry build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: github.event.inputs.publish == 'true'
    
    - name: Commit changes
      if: github.event.inputs.release == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update package version to ${{ env.VERSION }}"
        git push

    - name: Create GitHub release
      uses: actions/create-release@v1
      if: github.event.inputs.release == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false