name: Update and Publish Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "RClone version to build bindings for"
        required: true
        type: string
jobs:
  update-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      VERSION: ${{ github.event.inputs.version || github.event.release.tag_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Fuse bindings
      run: sudo apt-get install -y fuse3 libfuse3-dev
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipx
        python -m pipx ensurepath
    
    - name: Install poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Configure Poetry
      run: poetry config virtualenvs.create false
        
    - name: Set version
      run: poetry version ${{ env.VERSION }}
    
    - name: Build package
      run: poetry build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1